export const ROUTES = {
    ABOUT: "/about",
    BLOG: (slug: string) => `/blogs/${slug}`,
    BLOGS: "/blogs",
    EDUCATION: "/education",
    EDUCATION_DETAIL: (educationId: string) => `/education/${educationId}`,
    EXPERIENCE: "/experience",
    EXPERIENCE_DETAIL: (slug: string) => `/experience/${slug}`,
    HOME: "/",
    PRIVACY_POLICY: "/privacy-policy",
    PROJECT: (projectId: string) => `/projects/${projectId}`,
    PROJECTS: "/projects",
    PROJECTS_STARTERS: "/projects#starters",
    RESUME: "/resume",
    RESUME_PDF: "/resume.pdf",
    SITEMAP: "/sitemap",
    SKILLS: "/skills",
    TERMS: "/terms-and-conditions",
} as const;
